-- 예매를 하면, 해당 영화 상영 시간의 예매 가능 좌석을 수정해주는 트리거 작성 및 테스트
USE CGV;
DROP TRIGGER IF EXISTS TICKETING_UPDATE_SEAT;
DELIMITER $$
CREATE TRIGGER TICKETING_UPDATE_SEAT
AFTER INSERT
ON TICKETING
FOR EACH ROW
BEGIN

UPDATE SCREEN_SCHEDULE
	SET SS_POSSIBLE_SEAT = SS_POSSIBLE_SEAT -NEW.TI_AMOUNT
    WHERE SS_NUM = NEW.TI_SS_NUM;
	
END $$
DELIMITER ;

SELECT * FROM SCREEN_SCHEDULE;

INSERT INTO TICKETING(TI_AMOUNT, TI_SS_NUM, TI_ME_ID, TI_TOTAL_PRICE)
	VALUE(3, 20, 'ABC', 30000);
